// Synthetic merchant catalogs for the Molecule demo. Every product is tagged MOLECULE_DEMO.
// Deterministic: same input -> same handles, prices and stock, so seeding is idempotent.
const hashStr = (s) => {
  let x = 2166136261;
  for (const c of s) {
    x ^= c.charCodeAt(0);
    x = Math.imul(x, 16777619);
  }
  return x >>> 0;
};
const rng = (seed) => {
  let a = hashStr(seed);
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
};
export const slug = (s) =>
  s
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
const money = (n) => (Math.round(n * 100) / 100).toFixed(2);
const cartesian = (opts) =>
  Object.entries(opts).reduce(
    (acc, [name, vals]) =>
      acc.flatMap((combo) =>
        vals.map((v) => [...combo, { optionName: name, name: v }]),
      ),
    [[]],
  );
const val = (combo, name) => combo.find((c) => c.optionName === name)?.name;

const VENDORS = {
  molecule: "Molecule",
  basegoods: "BaseGoods",
  stitchworks: "StitchWorks",
  threadforge: "ThreadForge",
  needlenorth: "NeedleNorth",
  laserlab: "LaserLab",
  packship: "PackShip",
  snackbox: "SnackBox",
  printpress: "PrintPress",
};
export const MERCHANT_IDS = {
  basegoods: "base-goods",
  stitchworks: "stitch-works",
  threadforge: "thread-forge",
  needlenorth: "needle-north",
  laserlab: "laser-lab",
  packship: "pack-ship",
  snackbox: "snack-box",
  molecule: "molecule",
  printpress: "print-press",
};

function build(role, p) {
  const {
    title,
    type,
    desc,
    tags = [],
    options = null,
    price,
    stock = [40, 400],
    kind = "supply",
    exact = false,
  } = p;
  const r = rng(role + "|" + title);
  const opts = options ?? { Title: ["Default Title"] };
  const variants = cartesian(opts).map((combo, i) => {
    const raw = typeof price === "function" ? price(combo, i) : price;
    const jitter = typeof price === "function" || exact ? 1 : 0.96 + r() * 0.08;
    return {
      optionValues: combo,
      price: money(raw * jitter),
      sku: `${role.slice(0, 3)}-${slug(title).slice(0, 24)}-${i + 1}`.toUpperCase(),
      tracked: stock !== null,
      quantity: stock
        ? Math.round(stock[0] + r() * (stock[1] - stock[0]))
        : null,
    };
  });
  return {
    handle: `${role}-${slug(title)}`.slice(0, 200),
    title,
    type,
    vendor: VENDORS[role] ?? role,
    descriptionHtml: `<p>Synthetic demonstration data; not a verified merchant quote.</p><p>${desc}</p>`,
    tags: [
      "MOLECULE_DEMO",
      `merchant:${MERCHANT_IDS[role] ?? role}`,
      `kind:${kind}`,
      ...tags,
    ],
    options: opts,
    variants,
  };
}

const TIERS = ["12-24", "25-49", "50-99", "100-249", "250+"];
const TIER_F = [1, 0.9, 0.8, 0.7, 0.6];
function svc(
  role,
  title,
  type,
  desc,
  base,
  {
    tiers = TIERS,
    factors = TIER_F,
    kind = "transform",
    lead = 5,
    leadText = null,
    tags = [],
  } = {},
) {
  const leadTxt = leadText ?? `Standard lead time: ${lead} business days.`;
  return build(role, {
    title,
    type,
    desc: `${desc} ${leadTxt}`,
    tags: [
      `lead_time:${slug(leadText ?? lead + " business days")}`,
      "service",
      ...tags,
    ],
    options: { Quantity: tiers },
    price: (c) => base * factors[tiers.indexOf(val(c, "Quantity"))],
    stock: null,
    kind,
    exact: true,
  });
}
const fee = (role, title, type, desc, amount, kind = "transform", tags = []) =>
  build(role, {
    title,
    type,
    desc,
    tags: ["service", "fee", ...tags],
    price: amount,
    stock: null,
    kind,
    exact: true,
  });
const capacity = (role, title, perDay, kind) =>
  build(role, {
    title,
    type: "Capacity",
    desc: `Live daily capacity indicator: inventory equals units available per day. Setting this to 0 marks the merchant unavailable.`,
    tags: ["capacity", "live-signal"],
    price: 0,
    stock: [perDay, perDay],
    kind,
    exact: true,
  });

const C10 = [
  "Black",
  "White",
  "Navy",
  "Heather Grey",
  "Forest Green",
  "Maroon",
  "Royal Blue",
  "Sand",
  "Red",
  "Charcoal",
];
const C8 = C10.slice(0, 8),
  C6 = C10.slice(0, 6),
  C4 = ["Black", "Navy", "Grey", "White"],
  C3 = ["Black", "Navy", "Grey"];
const SZ = ["S", "M", "L", "XL", "2XL"];

// ---------------------------------------------------------------- BaseGoods (blanks of every kind)
// row: name, type, material, description, base price, option name, option values, colors
const GOODS = [
  [
    "Classic Pullover Hoodie 8oz",
    "Hoodies",
    "cotton",
    "Midweight 100% cotton pullover hoodie with kangaroo pocket. Ideal for embroidery and screen print.",
    24,
    "Size",
    SZ,
    C8,
  ],
  [
    "Heavyweight Pullover Hoodie 12oz",
    "Hoodies",
    "cotton-poly-blend",
    "12oz 80/20 cotton-polyester fleece with double-lined hood.",
    31,
    "Size",
    SZ,
    C6,
  ],
  [
    "Performance Hoodie",
    "Hoodies",
    "polyester",
    "100% polyester moisture-wicking hoodie. Contains no cotton.",
    19,
    "Size",
    SZ,
    C4,
  ],
  [
    "Zip-Up Hoodie",
    "Hoodies",
    "cotton",
    "Full-zip 100% cotton hoodie with metal zipper.",
    29,
    "Size",
    SZ,
    C6,
  ],
  [
    "Organic Cotton Hoodie",
    "Hoodies",
    "organic-cotton",
    "GOTS-certified organic cotton hoodie, midweight.",
    38,
    "Size",
    SZ,
    C4,
  ],
  [
    "Crewneck Sweatshirt",
    "Sweatshirts",
    "cotton",
    "Classic 100% cotton crewneck sweatshirt.",
    22,
    "Size",
    SZ,
    C6,
  ],
  [
    "Quarter-Zip Pullover",
    "Sweatshirts",
    "cotton-poly-blend",
    "Lightweight quarter-zip, cotton-polyester blend.",
    30,
    "Size",
    SZ,
    C4,
  ],
  [
    "Classic T-Shirt 5.3oz",
    "T-Shirts",
    "cotton",
    "100% cotton crew tee, unisex fit.",
    6.5,
    "Size",
    SZ,
    C10,
  ],
  [
    "Premium Ringspun T-Shirt",
    "T-Shirts",
    "cotton",
    "Soft ringspun cotton tee with a retail fit.",
    9.5,
    "Size",
    SZ,
    C8,
  ],
  [
    "Long Sleeve T-Shirt",
    "T-Shirts",
    "cotton",
    "100% cotton long sleeve tee.",
    11,
    "Size",
    SZ,
    C6,
  ],
  [
    "Performance T-Shirt",
    "T-Shirts",
    "polyester",
    "100% polyester moisture-wicking tee.",
    10,
    "Size",
    SZ,
    C6,
  ],
  [
    "Pique Polo",
    "Polos",
    "cotton",
    "Cotton pique polo with three-button placket.",
    17,
    "Size",
    SZ,
    C6,
  ],
  [
    "Performance Polo",
    "Polos",
    "polyester",
    "100% polyester UV-protective polo.",
    18,
    "Size",
    SZ,
    C4,
  ],
  [
    "Fleece Joggers",
    "Bottoms",
    "cotton-poly-blend",
    "Tapered fleece joggers with pockets.",
    26,
    "Size",
    SZ,
    C4,
  ],
  [
    "Athletic Shorts",
    "Bottoms",
    "polyester",
    "Lightweight polyester athletic shorts.",
    14,
    "Size",
    SZ,
    C4,
  ],
  [
    "Softshell Jacket",
    "Outerwear",
    "polyester",
    "Water-resistant softshell jacket.",
    44,
    "Size",
    SZ,
    C4,
  ],
  [
    "Puffer Vest",
    "Outerwear",
    "polyester",
    "Quilted puffer vest, recycled polyester fill.",
    39,
    "Size",
    SZ,
    ["Black", "Navy", "Olive"],
  ],
  [
    "Windbreaker",
    "Outerwear",
    "nylon",
    "Packable nylon windbreaker.",
    34,
    "Size",
    SZ,
    C4,
  ],
  [
    "Varsity Jacket",
    "Outerwear",
    "wool-blend",
    "Wool-blend body with faux leather sleeves.",
    68,
    "Size",
    SZ,
    ["Navy and Cream", "Black and White", "Green and Cream"],
  ],
  [
    "Kids Hoodie",
    "Kids",
    "cotton",
    "Youth 100% cotton pullover hoodie.",
    18,
    "Size",
    ["XS", "S", "M", "L"],
    C4,
  ],
  [
    "Kids T-Shirt",
    "Kids",
    "cotton",
    "Youth 100% cotton tee.",
    6,
    "Size",
    ["XS", "S", "M", "L"],
    C6,
  ],
  [
    "Crew Socks",
    "Accessories",
    "cotton-blend",
    "Cushioned cotton-blend crew socks.",
    4.5,
    "Size",
    ["S/M", "L/XL"],
    C4,
  ],
  [
    "Canvas Apron",
    "Accessories",
    "cotton",
    "12oz cotton canvas apron with adjustable strap.",
    12,
    null,
    null,
    C4,
  ],
  [
    "Twill Baseball Cap",
    "Headwear",
    "cotton",
    "Structured 6-panel cotton twill cap.",
    7,
    null,
    null,
    C8,
  ],
  [
    "Unstructured Dad Hat",
    "Headwear",
    "cotton",
    "Relaxed cotton dad hat with curved brim.",
    8,
    null,
    null,
    C6,
  ],
  [
    "Knit Beanie",
    "Headwear",
    "acrylic",
    "Cuffed acrylic knit beanie.",
    7.5,
    null,
    null,
    C6,
  ],
  [
    "Bucket Hat",
    "Headwear",
    "cotton",
    "Cotton twill bucket hat.",
    9,
    null,
    null,
    C4,
  ],
  [
    "Snapback Cap",
    "Headwear",
    "cotton-poly-blend",
    "Flat-brim snapback cap.",
    9.5,
    null,
    null,
    C6,
  ],
  [
    "Trucker Hat",
    "Headwear",
    "polyester",
    "Foam-front mesh-back trucker hat.",
    6.5,
    null,
    null,
    C6,
  ],
  [
    "Canvas Tote Bag 10oz",
    "Bags",
    "cotton",
    "10oz cotton canvas tote, 15in x 16in.",
    6.5,
    null,
    null,
    C6,
  ],
  [
    "Organic Cotton Tote",
    "Bags",
    "organic-cotton",
    "Certified organic cotton tote.",
    8,
    null,
    null,
    C4,
  ],
  [
    "Drawstring Backpack",
    "Bags",
    "polyester",
    "Lightweight polyester drawstring bag.",
    4.5,
    null,
    null,
    C6,
  ],
  [
    "Laptop Backpack",
    "Bags",
    "polyester",
    "Padded 15in laptop backpack with USB port.",
    32,
    null,
    null,
    C4,
  ],
  [
    "Weekender Duffel",
    "Bags",
    "polyester",
    "Water-resistant 40L duffel.",
    38,
    null,
    null,
    C4,
  ],
  [
    "Belt Bag",
    "Bags",
    "polyester",
    "Zippered belt bag with adjustable strap.",
    14,
    null,
    null,
    C4,
  ],
  [
    "Insulated Cooler Bag",
    "Bags",
    "polyester",
    "Insulated 12-can cooler bag.",
    22,
    null,
    null,
    C4,
  ],
  [
    "Insulated Lunch Bag",
    "Bags",
    "polyester",
    "Insulated zip lunch bag.",
    12,
    null,
    null,
    C4,
  ],
  [
    "Jute Market Tote",
    "Bags",
    "jute",
    "Natural jute tote with cotton lining.",
    9,
    null,
    null,
    ["Natural"],
  ],
  [
    "Stainless Steel Water Bottle",
    "Drinkware",
    "stainless-steel",
    "Double-wall vacuum insulated bottle with BPA-free lid.",
    12,
    "Size",
    ["500ml", "750ml", "1L"],
    [
      "Matte Black",
      "White",
      "Navy",
      "Forest Green",
      "Rose Gold",
      "Silver",
      "Sky Blue",
      "Coral",
    ],
  ],
  [
    "Insulated Tumbler",
    "Drinkware",
    "stainless-steel",
    "Vacuum-insulated tumbler with slider lid.",
    14,
    "Size",
    ["20oz", "30oz"],
    ["Matte Black", "White", "Navy", "Forest Green", "Rose Gold", "Silver"],
  ],
  [
    "Ceramic Coffee Mug",
    "Drinkware",
    "ceramic",
    "Dishwasher-safe ceramic mug.",
    4.5,
    "Size",
    ["11oz", "15oz"],
    ["White", "Black", "Navy", "Speckle Grey", "Sage Green"],
  ],
  [
    "Travel Coffee Mug",
    "Drinkware",
    "stainless-steel",
    "Spill-resistant insulated travel mug.",
    11,
    null,
    null,
    ["Black", "White", "Navy", "Silver"],
  ],
  [
    "Glass Water Bottle",
    "Drinkware",
    "glass",
    "Borosilicate glass bottle with silicone sleeve.",
    10,
    "Size",
    ["500ml", "750ml"],
    ["Clear", "Smoke", "Blue"],
  ],
  [
    "Wine Tumbler 12oz",
    "Drinkware",
    "stainless-steel",
    "Stemless insulated wine tumbler.",
    13,
    null,
    null,
    ["White", "Black", "Rose Gold", "Navy"],
  ],
  [
    "Can Cooler",
    "Drinkware",
    "neoprene",
    "Collapsible neoprene can cooler.",
    1.8,
    null,
    null,
    C6,
  ],
  [
    "Shaker Bottle 700ml",
    "Drinkware",
    "plastic",
    "BPA-free shaker with agitator ball.",
    5.5,
    null,
    null,
    C4,
  ],
  [
    "Enamel Camp Mug",
    "Drinkware",
    "enamel-steel",
    "Speckled enamel camping mug.",
    7,
    null,
    null,
    ["White", "Black", "Blue", "Green"],
  ],
  [
    "Coffee Thermos 1L",
    "Drinkware",
    "stainless-steel",
    "Insulated 1L coffee thermos.",
    19,
    null,
    null,
    ["Black", "Silver", "Green"],
  ],
  [
    "Pint Glass 16oz",
    "Drinkware",
    "glass",
    "Classic 16oz pint glass.",
    2.8,
    null,
    null,
    ["Clear"],
  ],
  [
    "Whiskey Glass 10oz",
    "Drinkware",
    "glass",
    "Heavy-base 10oz rocks glass.",
    3.5,
    null,
    null,
    ["Clear"],
  ],
  [
    "Bamboo Travel Cup",
    "Drinkware",
    "bamboo",
    "Bamboo-fiber travel cup with lid.",
    6,
    null,
    null,
    ["Natural", "Black"],
  ],
  [
    "Hardcover Notebook A5",
    "Stationery",
    "paper",
    "A5 hardcover notebook, 192 dotted pages.",
    6.5,
    null,
    null,
    C6,
  ],
  [
    "Softcover Notebook A6",
    "Stationery",
    "paper",
    "A6 softcover pocket notebook, 96 pages.",
    2.4,
    null,
    null,
    C6,
  ],
  [
    "Spiral Notebook",
    "Stationery",
    "paper",
    "Spiral-bound ruled notebook, 80 sheets.",
    3.2,
    null,
    null,
    C4,
  ],
  [
    "Leatherette Journal",
    "Stationery",
    "pu-leather",
    "Faux-leather journal with ribbon marker.",
    9,
    null,
    null,
    ["Black", "Brown", "Navy", "Burgundy"],
  ],
  [
    "Metal Ballpoint Pen",
    "Stationery",
    "aluminum",
    "Twist-action aluminum ballpoint pen.",
    1.6,
    null,
    null,
    C6,
  ],
  [
    "Gel Pen 3-Pack",
    "Stationery",
    "plastic",
    "Smooth-writing gel pens.",
    2.5,
    null,
    null,
    ["Black Ink", "Blue Ink", "Assorted"],
  ],
  [
    "Pen and Notebook Gift Set",
    "Stationery",
    "mixed",
    "Boxed A5 notebook and metal pen.",
    11,
    null,
    null,
    C4,
  ],
  [
    "Desk Pad",
    "Stationery",
    "pu-leather",
    "Large vegan-leather desk pad.",
    16,
    null,
    null,
    ["Black", "Grey", "Tan"],
  ],
  [
    "Mouse Pad",
    "Stationery",
    "neoprene",
    "Non-slip neoprene mouse pad.",
    3.2,
    null,
    null,
    C4,
  ],
  [
    "Woven Lanyard",
    "Stationery",
    "polyester",
    "Polyester lanyard with metal clip.",
    1.1,
    null,
    null,
    C10,
  ],
  [
    "Badge Holder",
    "Stationery",
    "plastic",
    "Clear vertical badge holder.",
    0.7,
    null,
    null,
    ["Clear", "Black"],
  ],
  [
    "Sticky Note Set",
    "Stationery",
    "paper",
    "Assorted colour sticky note set.",
    2.8,
    null,
    null,
    ["Assorted"],
  ],
  [
    "Pencil Case",
    "Stationery",
    "canvas",
    "Zippered canvas pencil case.",
    4.4,
    null,
    null,
    C6,
  ],
  [
    "Undated Weekly Planner",
    "Stationery",
    "paper",
    "Undated 52-week planner.",
    7.5,
    null,
    null,
    C4,
  ],
  [
    "2027 Wall Calendar",
    "Stationery",
    "paper",
    "12-month wall calendar for 2027.",
    5.5,
    null,
    null,
    ["Standard"],
  ],
  [
    "Wireless Charger 15W",
    "Tech",
    "plastic",
    "Qi-certified 15W wireless charging pad.",
    12,
    null,
    null,
    ["Black", "White"],
  ],
  [
    "Power Bank 10000mAh",
    "Tech",
    "aluminum",
    "10000mAh USB-C power bank.",
    14,
    null,
    null,
    ["Black", "White", "Silver"],
  ],
  [
    "3-in-1 Charging Cable",
    "Tech",
    "nylon",
    "USB-C, Lightning and Micro-USB braided cable.",
    3.5,
    null,
    null,
    C4,
  ],
  [
    "USB Flash Drive 32GB",
    "Tech",
    "metal",
    "32GB USB 3.0 metal flash drive.",
    5.5,
    null,
    null,
    ["Silver", "Black"],
  ],
  [
    "Wireless Earbuds",
    "Tech",
    "plastic",
    "Bluetooth 5.3 earbuds with charging case.",
    19,
    null,
    null,
    ["Black", "White"],
  ],
  [
    "Bluetooth Speaker",
    "Tech",
    "plastic",
    "Portable water-resistant speaker.",
    17,
    null,
    null,
    ["Black", "Blue", "Red"],
  ],
  [
    "Laptop Sleeve",
    "Tech",
    "neoprene",
    "Padded neoprene laptop sleeve.",
    9,
    "Size",
    ["13in", "15in"],
    C3,
  ],
  [
    "Phone Stand",
    "Tech",
    "aluminum",
    "Foldable aluminum phone stand.",
    3.8,
    null,
    null,
    ["Silver", "Black"],
  ],
  [
    "Webcam Cover 3-Pack",
    "Tech",
    "plastic",
    "Slide privacy webcam covers.",
    1.2,
    null,
    null,
    ["Black"],
  ],
  [
    "Cable Organizer Pouch",
    "Tech",
    "polyester",
    "Zip tech organizer pouch.",
    6.5,
    null,
    null,
    C3,
  ],
  [
    "Phone Wallet Sleeve",
    "Tech",
    "silicone",
    "Stick-on silicone card sleeve.",
    1.5,
    null,
    null,
    C6,
  ],
  [
    "Soy Candle 8oz",
    "Home",
    "soy-wax",
    "Hand-poured soy candle in glass jar, 45 hour burn.",
    8.5,
    null,
    null,
    ["Vanilla", "Lavender", "Cedar", "Sea Salt", "Citrus", "Eucalyptus"],
  ],
  [
    "Reed Diffuser",
    "Home",
    "glass",
    "Reed diffuser, 100ml.",
    9,
    null,
    null,
    ["Vanilla", "Lavender", "Sandalwood"],
  ],
  [
    "Fleece Blanket",
    "Home",
    "polyester",
    "Soft fleece throw, 50 x 60in.",
    14,
    null,
    null,
    ["Grey", "Navy", "Cream", "Black"],
  ],
  [
    "Throw Pillow Cover",
    "Home",
    "cotton",
    "Cotton canvas pillow cover, 18 x 18in.",
    6,
    null,
    null,
    C4,
  ],
  [
    "Cork Coaster Set",
    "Home",
    "cork",
    "Set of 4 cork coasters.",
    4.5,
    null,
    null,
    ["Natural"],
  ],
  [
    "Ceramic Planter",
    "Home",
    "ceramic",
    "Small ceramic planter with drainage.",
    7,
    null,
    null,
    ["White", "Terracotta", "Black"],
  ],
  [
    "Wooden Picture Frame",
    "Home",
    "wood",
    "Solid wood 5 x 7in frame.",
    6.5,
    null,
    null,
    ["Walnut", "Natural", "Black"],
  ],
  [
    "Wall Clock",
    "Home",
    "wood",
    "Silent 12in wall clock.",
    13,
    null,
    null,
    ["Walnut", "White"],
  ],
  [
    "Bath Towel",
    "Home",
    "cotton",
    "Cotton bath towel, 27 x 54in.",
    8.5,
    null,
    null,
    C4,
  ],
  [
    "Beach Towel",
    "Home",
    "cotton",
    "Velour beach towel, 30 x 60in.",
    11,
    null,
    null,
    ["Navy", "Stripe", "White"],
  ],
  [
    "Bamboo Cutting Board",
    "Home",
    "bamboo",
    "Bamboo cutting board with juice groove.",
    11,
    "Size",
    ["Small", "Large"],
    ["Natural"],
  ],
  [
    "Cheese Board Set",
    "Home",
    "acacia-wood",
    "Acacia board with knife set.",
    19,
    null,
    null,
    ["Natural"],
  ],
  [
    "Serving Tray",
    "Home",
    "wood",
    "Wooden serving tray with handles.",
    12,
    null,
    null,
    ["Walnut", "Natural"],
  ],
  [
    "Dog Bandana",
    "Pets",
    "cotton",
    "Cotton dog bandana.",
    3.2,
    "Size",
    ["S", "M", "L"],
    C4,
  ],
  [
    "Stainless Pet Bowl",
    "Pets",
    "stainless-steel",
    "Non-slip stainless pet bowl.",
    6.5,
    "Size",
    ["S", "L"],
    ["Silver"],
  ],
  [
    "Nylon Dog Leash",
    "Pets",
    "nylon",
    "5ft nylon dog leash.",
    5.5,
    null,
    null,
    C4,
  ],
  [
    "Plush Pet Bed",
    "Pets",
    "polyester",
    "Plush round pet bed.",
    22,
    "Size",
    ["S", "M", "L"],
    ["Grey", "Tan"],
  ],
  [
    "Rope Chew Toy",
    "Pets",
    "cotton",
    "Cotton rope dog toy.",
    3,
    null,
    null,
    ["Assorted"],
  ],
  [
    "Lip Balm 3-Pack",
    "Wellness",
    "beeswax",
    "Natural beeswax lip balm.",
    3.5,
    null,
    null,
    ["Mint", "Vanilla", "Cherry"],
  ],
  [
    "Hand Cream",
    "Wellness",
    "shea-butter",
    "Shea butter hand cream, 50ml.",
    5,
    null,
    null,
    ["Lavender", "Unscented", "Citrus"],
  ],
  [
    "Bar Soap",
    "Wellness",
    "plant-oil",
    "Cold-process bar soap.",
    4,
    null,
    null,
    ["Oatmeal", "Lavender", "Charcoal"],
  ],
  [
    "Bath Bomb Set",
    "Wellness",
    "mixed",
    "Set of 4 bath bombs.",
    9,
    null,
    null,
    ["Assorted"],
  ],
  [
    "Sunscreen Stick SPF50",
    "Wellness",
    "mineral",
    "Mineral SPF50 sunscreen stick.",
    6.5,
    null,
    null,
    ["Unscented"],
  ],
  [
    "Yoga Mat 6mm",
    "Wellness",
    "tpe",
    "Non-slip 6mm yoga mat.",
    17,
    null,
    null,
    ["Black", "Purple", "Teal", "Grey"],
  ],
  [
    "Resistance Band Set",
    "Wellness",
    "latex",
    "Set of 5 resistance bands.",
    9,
    null,
    null,
    ["Assorted"],
  ],
  [
    "Sports Towel",
    "Wellness",
    "microfiber",
    "Quick-dry microfiber towel.",
    5.5,
    null,
    null,
    C4,
  ],
  [
    "Compact Umbrella",
    "Outdoor",
    "polyester",
    "Windproof auto-open umbrella.",
    11,
    null,
    null,
    C4,
  ],
  [
    "Polarized Sunglasses",
    "Outdoor",
    "polycarbonate",
    "UV400 polarized sunglasses.",
    5.5,
    null,
    null,
    ["Black", "Tortoise", "Clear"],
  ],
  [
    "Flying Disc",
    "Outdoor",
    "plastic",
    "9in flying disc.",
    1.9,
    null,
    null,
    C6,
  ],
  [
    "Picnic Blanket",
    "Outdoor",
    "polyester",
    "Waterproof-backed picnic blanket.",
    16,
    null,
    null,
    ["Plaid Red", "Plaid Blue", "Grey"],
  ],
  [
    "Folding Camp Chair",
    "Outdoor",
    "polyester",
    "Compact folding camp chair.",
    21,
    null,
    null,
    ["Black", "Green"],
  ],
  [
    "Playing Cards",
    "Fun",
    "paper",
    "Standard 52-card deck, custom-printable.",
    2.5,
    null,
    null,
    ["Black", "White"],
  ],
  [
    "Jigsaw Puzzle 500pc",
    "Fun",
    "cardboard",
    "500-piece jigsaw puzzle.",
    8,
    null,
    null,
    ["Blank"],
  ],
  [
    "Enamel Pin Blank",
    "Fun",
    "zinc-alloy",
    "Hard-enamel pin blank.",
    1.4,
    null,
    null,
    ["Gold", "Silver", "Black"],
  ],
  [
    "Keychain Blank",
    "Accessories",
    "metal",
    "Metal keychain blank.",
    1.2,
    null,
    null,
    ["Round", "Rectangle", "Bottle Opener", "Carabiner"],
  ],
  [
    "Luggage Tag",
    "Accessories",
    "pu-leather",
    "Leatherette luggage tag.",
    2.2,
    null,
    null,
    ["Black", "Brown", "Navy"],
  ],
  [
    "Sticker Pack",
    "Fun",
    "vinyl",
    "Assorted vinyl sticker pack.",
    2,
    null,
    null,
    ["Assorted"],
  ],
];

function baseGoods() {
  const out = [];
  for (const [name, type, mat, desc, base, optName, optVals, colors] of GOODS) {
    for (const color of colors) {
      const single = colors.length === 1;
      out.push(
        build("basegoods", {
          title: single ? name : `${name} - ${color}`,
          type,
          desc: `${desc}${single ? "" : ` Colour: ${color}.`} Blank, ready for decoration.`,
          tags: [
            `material:${mat}`,
            `category:${slug(type)}`,
            `color:${slug(color)}`,
            "blank",
          ],
          options: optName ? { [optName]: optVals } : null,
          price: optName
            ? (c) => base + optVals.indexOf(val(c, optName)) * base * 0.15
            : base,
          stock: [30, 400],
        }),
      );
    }
  }
  return out;
}

// ---------------------------------------------------------------- Embroidery (StitchWorks + ThreadForge)
function embroidery(role, mult, lead, perDay) {
  const S = (title, type, desc, base, o = {}) =>
    svc(role, title, type, desc, +(base * mult).toFixed(2), { lead, ...o });
  const F = (title, type, desc, amount, tags) =>
    fee(
      role,
      title,
      type,
      desc,
      +(amount * (mult > 1 ? 1.05 : 1)).toFixed(2),
      "transform",
      tags,
    );
  const out = [
    S(
      "Left-Chest Logo Embroidery (up to 5,000 stitches)",
      "Embroidery",
      "Standard left-chest logo embroidery on customer-supplied or supplied garments.",
      4.5,
    ),
    S(
      "Left-Chest Logo Embroidery (5,001-8,000 stitches)",
      "Embroidery",
      "Detailed left-chest logo embroidery.",
      6.25,
    ),
    S(
      "Full-Front Embroidery (8,001-15,000 stitches)",
      "Embroidery",
      "Large full-front embroidery for hoodies and jackets.",
      9.75,
    ),
    S(
      "Large Back Embroidery (15,001-25,000 stitches)",
      "Embroidery",
      "Large back-panel embroidery.",
      14.5,
    ),
    S(
      "Sleeve Embroidery",
      "Embroidery",
      "Small sleeve or cuff embroidery.",
      3.75,
    ),
    S(
      "Cap Front Embroidery (flat)",
      "Embroidery",
      "Flat embroidery on the front of caps and hats.",
      4.25,
    ),
    S(
      "Cap 3D Puff Embroidery",
      "Embroidery",
      "Raised 3D puff embroidery on cap fronts.",
      5.75,
    ),
    S(
      "Cap Side or Back Embroidery",
      "Embroidery",
      "Small embroidery on cap side or back.",
      3.25,
    ),
    S(
      "Beanie Cuff Embroidery",
      "Embroidery",
      "Embroidery on knit beanie cuffs.",
      4.5,
    ),
    S(
      "Tote and Bag Embroidery",
      "Embroidery",
      "Embroidery on canvas totes and bags.",
      5,
    ),
    S(
      "Towel Embroidery",
      "Embroidery",
      "Embroidery on bath and sports towels.",
      5.5,
    ),
    S("Apron Embroidery", "Embroidery", "Embroidery on aprons.", 5),
    S(
      "Jacket Left-Chest Embroidery",
      "Embroidery",
      "Left-chest embroidery on jackets and outerwear.",
      5.5,
    ),
    S(
      "Monogram and Name Personalization",
      "Personalization",
      "Names and monograms up to 12 characters.",
      3,
    ),
    S(
      "Patch Application (sew-on)",
      "Finishing",
      "Sew on customer-supplied patches.",
      2.5,
      { kind: "assemble" },
    ),
    S(
      "Metallic Thread Upcharge",
      "Upcharge",
      "Per-unit upcharge for metallic thread.",
      1.25,
    ),
    S(
      "Pantone Thread Color Match",
      "Upcharge",
      "Custom thread color matching per unit.",
      0.5,
    ),
    S(
      "Fold, Bag and Tag",
      "Finishing",
      "Fold, poly-bag and hangtag each finished piece.",
      0.6,
      { kind: "assemble" },
    ),
    S(
      "Quality Inspection (embroidery)",
      "Finishing",
      "Per-piece visual quality inspection.",
      0.25,
    ),
    F(
      "Digitizing - New Logo (setup)",
      "Setup",
      "One-time conversion of a logo into an embroidery file.",
      45,
      ["setup-fee"],
    ),
    F(
      "Digitizing - Revision",
      "Setup",
      "Revision to an existing embroidery file.",
      20,
      ["setup-fee"],
    ),
    F(
      "Rush 48h Surcharge",
      "Rush",
      "Per-order surcharge for 48-hour turnaround, subject to capacity.",
      75,
      ["rush"],
    ),
    F(
      "Rush 24h Surcharge",
      "Rush",
      "Per-order surcharge for 24-hour turnaround, subject to capacity.",
      150,
      ["rush"],
    ),
    F(
      "Sample Piece (1 unit)",
      "Samples",
      "One physical embroidered sample before the full run.",
      35,
      ["sample"],
    ),
    capacity(role, "Embroidery Capacity - Units per Day", perDay, "transform"),
  ];
  if (role === "threadforge") {
    out.push(
      S(
        "Custom Woven Patch",
        "Patches and Labels",
        "Woven patches with merrowed border, minimum 50.",
        1.9,
        {
          tiers: ["50-99", "100-249", "250-499", "500+"],
          factors: [1, 0.85, 0.7, 0.6],
          kind: "supply",
        },
      ),
      S(
        "Embroidered Iron-On Patch",
        "Patches and Labels",
        "Embroidered patches with iron-on backing.",
        2.1,
        {
          tiers: ["50-99", "100-249", "250-499", "500+"],
          factors: [1, 0.85, 0.7, 0.6],
          kind: "supply",
        },
      ),
      S(
        "PVC Rubber Patch",
        "Patches and Labels",
        "Soft PVC patches with velcro backing.",
        2.6,
        {
          tiers: ["50-99", "100-249", "250-499", "500+"],
          factors: [1, 0.85, 0.7, 0.6],
          kind: "supply",
        },
      ),
      S(
        "Chenille Letterman Patch",
        "Patches and Labels",
        "Chenille letter patches.",
        4.2,
        {
          tiers: ["25-49", "50-99", "100-249", "250+"],
          factors: [1, 0.9, 0.8, 0.7],
          kind: "supply",
        },
      ),
      S(
        "Woven Neck Label",
        "Patches and Labels",
        "Damask woven neck labels.",
        0.55,
        {
          tiers: ["250-499", "500-999", "1000-2499", "2500+"],
          factors: [1, 0.8, 0.65, 0.5],
          kind: "supply",
        },
      ),
      S(
        "Heat-Transfer Neck Label",
        "Patches and Labels",
        "Tagless heat-transfer labels.",
        0.4,
        {
          tiers: ["250-499", "500-999", "1000-2499", "2500+"],
          factors: [1, 0.8, 0.65, 0.5],
          kind: "supply",
        },
      ),
      S(
        "Printed Hangtags",
        "Patches and Labels",
        "Custom printed cardstock hangtags with string.",
        0.3,
        {
          tiers: ["250-499", "500-999", "1000-2499", "2500+"],
          factors: [1, 0.8, 0.65, 0.5],
          kind: "supply",
        },
      ),
      S(
        "Leather Patch",
        "Patches and Labels",
        "Debossed leather patches.",
        2.9,
        {
          tiers: ["50-99", "100-249", "250-499", "500+"],
          factors: [1, 0.85, 0.7, 0.6],
          kind: "supply",
        },
      ),
    );
  }
  return out;
}

// ---------------------------------------------------------------- LaserLab
function laserLab() {
  const R = "laserlab";
  const S = (t, ty, d, b, o = {}) => svc(R, t, ty, d, b, { lead: 4, ...o });
  const out = [
    S(
      "Water Bottle Engraving",
      "Engraving",
      "Laser engraving on stainless steel bottles: $3.20 per unit plus one setup fee per design.",
      3.2,
    ),
    S(
      "Tumbler Engraving",
      "Engraving",
      "Laser engraving on insulated tumblers.",
      3.6,
    ),
    S(
      "Mug Engraving",
      "Engraving",
      "Laser engraving on ceramic and enamel mugs.",
      3.4,
    ),
    S(
      "Wood Engraving",
      "Engraving",
      "Engraving on wood and bamboo items.",
      2.8,
    ),
    S(
      "Leather and Leatherette Engraving",
      "Engraving",
      "Engraving on leather goods.",
      2.6,
    ),
    S(
      "Metal Marking (fiber laser)",
      "Engraving",
      "Permanent marking on stainless steel, aluminum and brass.",
      3.9,
    ),
    S("Glass Etching", "Engraving", "Etching on glassware.", 4.2),
    S(
      "Acrylic Cutting and Engraving",
      "Engraving",
      "Cut and engraved acrylic signs and tags.",
      3.1,
    ),
    S("Pen Engraving", "Engraving", "Engraving on pens.", 1.8),
    S(
      "Keychain Engraving",
      "Engraving",
      "Engraving on keychains and tags.",
      1.6,
    ),
    S(
      "Photo Engraving on Wood",
      "Engraving",
      "Greyscale photo engraving on wood.",
      6.5,
    ),
    S("QR Code Engraving", "Engraving", "Scannable QR code engraving.", 2.2),
    S(
      "Serial Number Engraving",
      "Engraving",
      "Sequential serial numbers.",
      1.2,
    ),
    S(
      "Cork Coaster Engraving",
      "Engraving",
      "Engraving on cork coasters.",
      1.9,
    ),
    S(
      "UV Color Printing on Hard Goods",
      "Printing",
      "Full-color UV printing on bottles and hard goods.",
      5.5,
      { lead: 5 },
    ),
    fee(
      R,
      "Engraving Setup Fee (per design)",
      "Setup",
      "One-time file setup per design. Vector files (SVG, AI) preferred.",
      20,
      "transform",
      ["setup-fee"],
    ),
    fee(
      R,
      "Vector Artwork Cleanup",
      "Setup",
      "Convert raster artwork to vector for engraving.",
      35,
      "transform",
      ["setup-fee"],
    ),
    fee(
      R,
      "Rush 24h Engraving Surcharge",
      "Rush",
      "Per-order surcharge for 24-hour turnaround.",
      90,
      "transform",
      ["rush"],
    ),
    fee(
      R,
      "Engraved Sample (1 unit)",
      "Samples",
      "One engraved sample before the full run.",
      25,
      "transform",
      ["sample"],
    ),
    capacity(R, "Engraving Capacity - Units per Day", 250, "transform"),
  ];
  const blanks = [
    [
      "Bamboo Cutting Board Blank",
      "Blanks",
      "bamboo",
      9,
      "Size",
      ["Small", "Medium", "Large"],
      ["Natural"],
    ],
    [
      "Slate Coaster Set",
      "Blanks",
      "slate",
      8,
      null,
      null,
      ["Round", "Square"],
    ],
    [
      "Leatherette Patch Blank",
      "Blanks",
      "pu-leather",
      0.6,
      null,
      null,
      ["Black", "Brown", "Tan"],
    ],
    [
      "Acrylic Sign Blank",
      "Blanks",
      "acrylic",
      4.5,
      "Size",
      ["4x6in", "8x10in", "12x16in"],
      ["Clear", "Frosted", "Black"],
    ],
    [
      "Wooden Gift Box",
      "Blanks",
      "wood",
      7.5,
      "Size",
      ["Small", "Medium", "Large"],
      ["Natural", "Walnut"],
    ],
    [
      "Stainless Dog Tag",
      "Blanks",
      "stainless-steel",
      0.9,
      null,
      null,
      ["Silver", "Black", "Gold"],
    ],
    [
      "Wooden Ornament",
      "Blanks",
      "wood",
      1.1,
      null,
      null,
      ["Round", "Star", "Heart"],
    ],
    [
      "Stainless Flask 8oz",
      "Blanks",
      "stainless-steel",
      8.5,
      null,
      null,
      ["Silver", "Black", "Navy"],
    ],
    [
      "Brass Keychain",
      "Blanks",
      "brass",
      1.4,
      null,
      null,
      ["Round", "Rectangle"],
    ],
    ["Walnut Desk Organizer", "Blanks", "walnut", 22, null, null, ["Walnut"]],
    [
      "Wooden Phone Stand",
      "Blanks",
      "wood",
      5.2,
      null,
      null,
      ["Natural", "Walnut"],
    ],
    ["Whiskey Stone Set", "Blanks", "soapstone", 9.5, null, null, ["Grey"]],
    [
      "Wooden Pen",
      "Blanks",
      "wood",
      2.3,
      null,
      null,
      ["Maple", "Walnut", "Ebony"],
    ],
    [
      "Glass Tumbler 16oz",
      "Blanks",
      "glass",
      3.4,
      null,
      null,
      ["Clear", "Frosted"],
    ],
  ];
  for (const [name, type, mat, base, optName, optVals, colors] of blanks)
    for (const color of colors)
      out.push(
        build(R, {
          title: colors.length === 1 ? name : `${name} - ${color}`,
          type,
          desc: `Engraving-ready ${name.toLowerCase()}.`,
          tags: [`material:${mat}`, "engravable", "blank"],
          options: optName ? { [optName]: optVals } : null,
          price: optName
            ? (c) => base + optVals.indexOf(val(c, optName)) * base * 0.3
            : base,
          stock: [50, 500],
        }),
      );
  return out;
}

// ---------------------------------------------------------------- PackShip
function packShip() {
  const R = "packship";
  const goods = [
    [
      "Kraft Mailer Box",
      "Boxes",
      "Corrugated tuck-top mailer box.",
      0.95,
      "Size",
      ["Small 6x4x2in", "Medium 9x6x3in", "Large 12x9x4in", "XL 14x11x5in"],
      ["Kraft", "White", "Black"],
    ],
    [
      "Rigid Gift Box",
      "Boxes",
      "Rigid two-piece gift box with lid.",
      2.4,
      "Size",
      ["Small", "Medium", "Large"],
      ["White", "Black", "Kraft", "Navy"],
    ],
    [
      "Magnetic Closure Gift Box",
      "Boxes",
      "Rigid magnetic-closure gift box.",
      3.6,
      "Size",
      ["Small", "Medium", "Large"],
      ["White", "Black", "Navy"],
    ],
    [
      "Corrugated Shipping Box",
      "Boxes",
      "Standard RSC shipping box.",
      0.85,
      "Size",
      ["8x6x4in", "12x9x6in", "16x12x8in", "20x16x12in"],
      ["Brown", "White"],
    ],
    [
      "Poly Mailer",
      "Mailers",
      "Self-seal poly mailer.",
      0.18,
      "Size",
      ["6x9in", "10x13in", "14x17in"],
      ["White", "Black", "Grey"],
    ],
    [
      "Bubble Mailer",
      "Mailers",
      "Padded bubble mailer.",
      0.42,
      "Size",
      ["#0", "#2", "#5"],
      ["Kraft", "White"],
    ],
    [
      "Tissue Paper 100 Sheets",
      "Wrap",
      "Acid-free tissue paper.",
      6,
      null,
      null,
      ["White", "Black", "Kraft", "Blush", "Navy"],
    ],
    [
      "Kraft Paper Void Fill Roll",
      "Wrap",
      "Recycled kraft paper roll.",
      14,
      null,
      null,
      ["Brown"],
    ],
    [
      "Cardboard Sleeve",
      "Wrap",
      "Custom-fit cardboard sleeve.",
      0.3,
      null,
      null,
      ["Kraft", "White"],
    ],
    [
      "Muslin Drawstring Pouch",
      "Bags",
      "Cotton muslin drawstring pouch.",
      0.9,
      "Size",
      ["Small", "Medium", "Large"],
      ["Natural", "Black"],
    ],
    [
      "Satin Ribbon 25yd",
      "Wrap",
      "Satin ribbon roll.",
      4.5,
      null,
      null,
      ["Black", "White", "Navy", "Red", "Gold"],
    ],
    [
      "Thank-You Cards 50pk",
      "Inserts",
      "Blank thank-you cards with envelopes.",
      12,
      null,
      null,
      ["White", "Kraft"],
    ],
    [
      "Packing Tape 2in x 110yd",
      "Tape",
      "Acrylic packing tape.",
      2.8,
      null,
      null,
      ["Clear", "Kraft", "White"],
    ],
    [
      "Thermal Shipping Labels 4x6in",
      "Labels",
      "Thermal label roll, 250 labels.",
      7.5,
      null,
      null,
      ["White"],
    ],
    [
      "Fragile Stickers 500pk",
      "Labels",
      "Fragile warning stickers.",
      8.5,
      null,
      null,
      ["Red"],
    ],
    [
      "Gel Ice Pack",
      "Cold chain",
      "Reusable gel ice pack.",
      1.2,
      "Size",
      ["8oz", "16oz"],
      ["Blue"],
    ],
    [
      "Insulated Box Liner",
      "Cold chain",
      "Insulated shipper liner.",
      3.4,
      "Size",
      ["Small", "Large"],
      ["Silver"],
    ],
    [
      "Stand-Up Snack Pouch",
      "Food packaging",
      "Resealable food-safe stand-up pouch.",
      0.35,
      "Size",
      ["4oz", "8oz", "16oz"],
      ["Kraft", "White", "Black"],
    ],
    [
      "Food-Safe Kraft Tray",
      "Food packaging",
      "Grease-resistant kraft tray.",
      0.28,
      null,
      null,
      ["Kraft"],
    ],
    [
      "Corner Protectors 100pk",
      "Protective",
      "Cardboard edge protectors.",
      9,
      null,
      null,
      ["Brown"],
    ],
  ];
  const out = [];
  for (const [name, type, desc, base, optName, optVals, colors] of goods)
    for (const color of colors)
      out.push(
        build(R, {
          title: colors.length === 1 ? name : `${name} - ${color}`,
          type,
          desc,
          tags: ["packaging", `category:${slug(type)}`, `color:${slug(color)}`],
          options: optName ? { [optName]: optVals } : null,
          price: optName
            ? (c) => base + optVals.indexOf(val(c, optName)) * base * 0.25
            : base,
          stock: [200, 5000],
        }),
      );
  out.push(
    svc(
      R,
      "Custom Printed Mailer Box",
      "Boxes",
      "Full-colour custom printed mailer box.",
      2.9,
      {
        tiers: ["50-99", "100-249", "250-499", "500+"],
        factors: [1, 0.85, 0.7, 0.6],
        kind: "supply",
        lead: 12,
      },
    ),
    svc(
      R,
      "Kitting and Assembly (per kit)",
      "Assembly",
      "Assemble multi-item kits from inbound goods.",
      1.85,
      {
        kind: "assemble",
        lead: 3,
        leadText:
          "Lead time: 24 business hours after all inbound goods arrive.",
      },
    ),
    svc(
      R,
      "Individual Boxing",
      "Assembly",
      "Box each finished item individually.",
      0.65,
      { kind: "assemble", lead: 3, leadText: "Lead time: 1 day." },
    ),
    svc(
      R,
      "Pick and Pack (per item)",
      "Fulfillment",
      "Pick and pack items for shipment.",
      0.55,
      { kind: "fulfill", lead: 2 },
    ),
    svc(
      R,
      "Custom Insert Placement",
      "Assembly",
      "Place inserts, cards and samples.",
      0.25,
      { kind: "assemble", lead: 2 },
    ),
    svc(R, "Gift Wrapping", "Assembly", "Wrap and ribbon each item.", 1.6, {
      kind: "assemble",
      lead: 3,
    }),
    svc(
      R,
      "Barcode and SKU Labeling",
      "Assembly",
      "Apply barcode or SKU labels.",
      0.18,
      { kind: "assemble", lead: 2 },
    ),
    svc(R, "Shrink Wrapping", "Assembly", "Shrink-wrap finished items.", 0.35, {
      kind: "assemble",
      lead: 2,
    }),
    svc(
      R,
      "Quality Inspection (assembly)",
      "Assembly",
      "Per-piece inspection before dispatch.",
      0.3,
      { kind: "assemble", lead: 2 },
    ),
    svc(
      R,
      "Returns Processing",
      "Fulfillment",
      "Receive, inspect and restock returns.",
      2.4,
      { kind: "fulfill", lead: 3 },
    ),
    svc(
      R,
      "Dropship Fulfillment (per order)",
      "Fulfillment",
      "Ship individual orders direct to customers.",
      3.2,
      { kind: "fulfill", lead: 2 },
    ),
    svc(
      R,
      "International Customs Prep",
      "Fulfillment",
      "Customs forms and duties documentation.",
      4.5,
      { kind: "fulfill", lead: 3 },
    ),
    svc(
      R,
      "Inbound Receiving (per carton)",
      "Warehousing",
      "Receive and check in cartons.",
      0.9,
      { kind: "fulfill", lead: 1 },
    ),
    svc(
      R,
      "Cross-Dock Handling",
      "Warehousing",
      "Same-day transfer without storage.",
      0.4,
      { kind: "fulfill", lead: 1 },
    ),
    fee(
      R,
      "Rush Assembly 24h Surcharge",
      "Rush",
      "Per-order surcharge for 24-hour assembly.",
      95,
      "assemble",
      ["rush"],
    ),
    fee(
      R,
      "Pallet Storage (per pallet per month)",
      "Warehousing",
      "Monthly pallet storage.",
      22,
      "fulfill",
    ),
    fee(
      R,
      "Bin Storage (per bin per month)",
      "Warehousing",
      "Monthly bin storage.",
      4,
      "fulfill",
    ),
    fee(
      R,
      "Palletizing (per pallet)",
      "Warehousing",
      "Build and wrap an outbound pallet.",
      15,
      "fulfill",
    ),
    capacity(R, "Assembly Capacity - Kits per Day", 500, "assemble"),
  );
  return out;
}

// ---------------------------------------------------------------- SnackBox
const SNACKS = [
  [
    "Vegan Protein Bar",
    "Bars",
    "20g plant-protein bar.",
    2.1,
    [
      "Peanut Butter Crunch",
      "Chocolate Brownie",
      "Berry Almond",
      "Coconut Cashew",
      "Cookie Dough",
      "Lemon Cashew",
    ],
    ["soy", "tree-nut"],
  ],
  [
    "Fruit and Nut Bar",
    "Bars",
    "Date-sweetened fruit and nut bar.",
    1.7,
    ["Apple Cinnamon", "Cherry Cashew", "Mango Coconut", "Cocoa Almond"],
    ["tree-nut"],
  ],
  [
    "Trail Mix",
    "Nuts and Mixes",
    "Roasted trail mix.",
    1.9,
    [
      "Classic",
      "Tropical",
      "Spicy Mango",
      "Chocolate Cherry",
      "Salted Caramel",
    ],
    ["peanut", "tree-nut"],
  ],
  [
    "Roasted Nuts",
    "Nuts and Mixes",
    "Small-batch roasted nuts.",
    2.2,
    ["Almonds", "Cashews", "Pistachios", "Pecans", "Peanuts", "Walnuts"],
    ["tree-nut"],
  ],
  [
    "Kettle Chips",
    "Chips",
    "Kettle-cooked chips.",
    1.4,
    ["Sea Salt", "BBQ", "Sour Cream and Onion", "Jalapeno", "Salt and Vinegar"],
    [],
  ],
  [
    "Veggie Crisps",
    "Chips",
    "Baked veggie crisps.",
    1.5,
    ["Sweet Potato", "Beet", "Kale", "Mixed"],
    [],
  ],
  [
    "Oat Cookies",
    "Cookies",
    "Soft-baked vegan oat cookies.",
    1.6,
    [
      "Oatmeal Raisin",
      "Chocolate Chip",
      "Ginger Molasses",
      "Peanut Butter",
      "Double Chocolate",
    ],
    ["gluten", "soy"],
  ],
  [
    "Dark Chocolate Bar",
    "Chocolate",
    "70% dark chocolate.",
    2.4,
    ["Sea Salt", "Almond", "Orange", "Espresso", "Plain"],
    ["soy"],
  ],
  [
    "Dried Fruit Pack",
    "Dried Fruit",
    "Unsweetened dried fruit.",
    1.8,
    ["Mango", "Apple", "Cranberry", "Banana", "Pineapple"],
    [],
  ],
  [
    "Granola Pouch",
    "Granola",
    "Crunchy granola.",
    3.1,
    ["Maple Pecan", "Berry", "Cocoa", "Peanut Butter"],
    ["gluten", "tree-nut"],
  ],
  [
    "Mushroom Jerky",
    "Jerky",
    "Plant-based mushroom jerky.",
    3.4,
    ["Teriyaki", "Smoky BBQ", "Black Pepper"],
    ["soy"],
  ],
  [
    "Popcorn",
    "Popcorn",
    "Air-popped popcorn.",
    1.3,
    ["Sea Salt", "Kettle Corn", "White Cheddar", "Truffle"],
    [],
  ],
  [
    "Rice Crackers",
    "Crackers",
    "Baked rice crackers.",
    1.5,
    ["Sesame", "Seaweed", "Original"],
    ["sesame"],
  ],
  [
    "Loose Leaf Tea Tin",
    "Beverages",
    "Loose-leaf tea, 50g tin.",
    4.5,
    ["Earl Grey", "Green Jasmine", "Peppermint", "Chai", "Hibiscus"],
    [],
  ],
  [
    "Ground Coffee Bag",
    "Beverages",
    "Fair-trade ground coffee, 227g.",
    8.5,
    ["Medium Roast", "Dark Roast", "Decaf", "Cold Brew Blend"],
    [],
  ],
  [
    "Sparkling Water",
    "Beverages",
    "Zero-sugar sparkling water.",
    0.9,
    ["Lemon", "Berry", "Grapefruit", "Plain"],
    [],
  ],
  [
    "Oat Milk Latte Can",
    "Beverages",
    "Ready-to-drink oat latte.",
    2.8,
    ["Vanilla", "Mocha", "Original"],
    ["gluten"],
  ],
  [
    "Hot Sauce Mini",
    "Pantry",
    "Mini hot sauce bottle.",
    2.6,
    ["Mild", "Medium", "Extra Hot"],
    [],
  ],
  [
    "Nut Butter Squeeze Pack",
    "Pantry",
    "Single-serve nut butter.",
    1.4,
    ["Almond", "Peanut", "Cashew"],
    ["tree-nut"],
  ],
];
const GIFT_PACKS = [
  ["Snack Gift Pack - Classic", 28],
  ["Snack Gift Pack - Deluxe", 46],
  ["Snack Gift Pack - Party", 62],
  ["Coffee and Cookies Box", 34],
  ["Tea Lover Box", 30],
  ["Protein Power Box", 38],
  ["Movie Night Snack Box", 26],
  ["Office Snack Drawer Box", 55],
  ["Holiday Treat Box", 42],
  ["Healthy Break Box", 33],
  ["Chocolate Lover Box", 36],
  ["Spicy Snack Box", 29],
];
function snackBox() {
  const R = "snackbox";
  const packs = ["6 count", "12 count", "24 count", "48 count"];
  const counts = [6, 12, 24, 48];
  const disc = [1, 0.95, 0.9, 0.85];
  const out = [];
  let n = 0;
  for (const [name, type, desc, unit, flavors, allergens] of SNACKS)
    for (const flavor of flavors) {
      n++;
      const unverified = n % 17 === 0;
      const al =
        flavor === "Peanuts" ||
        flavor === "Peanut Butter" ||
        flavor === "Peanut Butter Crunch"
          ? [
              ...new Set([
                ...allergens.filter((a) => a !== "tree-nut"),
                "peanut",
              ]),
            ]
          : allergens;
      out.push(
        build(R, {
          title: `${name} - ${flavor}`,
          type,
          desc: `${desc} Vegan. ${unverified ? "Allergen statement pending from co-packer." : al.length ? `Contains: ${al.join(", ")}.` : "No major allergens declared."}`,
          tags: [
            "vegan",
            `category:${slug(type)}`,
            ...(unverified
              ? ["allergens:unverified"]
              : al.length
                ? al.map((a) => `allergen:${a}`)
                : ["allergen:none-declared"]),
            ...(al.includes("gluten") ? [] : ["gluten-free"]),
            `flavor:${slug(flavor)}`,
          ],
          options: { "Pack Size": packs },
          price: (c) => {
            const i = packs.indexOf(val(c, "Pack Size"));
            return unit * counts[i] * disc[i];
          },
          stock: [100, 1500],
        }),
      );
    }
  for (const [name, base] of GIFT_PACKS)
    out.push(
      build(R, {
        title: name,
        type: "Gift Packs",
        desc: "Assembled vegan snack gift pack in a kraft gift box. Made to order.",
        tags: ["vegan", "gift-pack", "assembled"],
        options: { Quantity: ["6 packs", "12 packs", "24 packs", "50 packs"] },
        price: (c) =>
          base *
          [1, 0.95, 0.9, 0.84][
            ["6 packs", "12 packs", "24 packs", "50 packs"].indexOf(
              val(c, "Quantity"),
            )
          ],
        stock: null,
        kind: "assemble",
        exact: true,
      }),
    );
  return out;
}

// ---------------------------------------------------------------- PrintPress
function printPress() {
  const R = "printpress";
  const T5 = ["50-99", "100-249", "250-499", "500-999", "1000+"];
  const F5 = [1, 0.8, 0.6, 0.45, 0.35];
  const S = (t, ty, d, b, o = {}) =>
    svc(R, t, ty, d, b, {
      tiers: T5,
      factors: F5,
      lead: 5,
      kind: "transform",
      ...o,
    });
  const out = [
    S(
      "Die-Cut Vinyl Stickers 2in",
      "Stickers",
      "Waterproof die-cut vinyl stickers, 2in.",
      0.35,
    ),
    S(
      "Die-Cut Vinyl Stickers 3in",
      "Stickers",
      "Waterproof die-cut vinyl stickers, 3in.",
      0.48,
    ),
    S(
      "Die-Cut Vinyl Stickers 4in",
      "Stickers",
      "Waterproof die-cut vinyl stickers, 4in.",
      0.65,
    ),
    S(
      "Kiss-Cut Sticker Sheets",
      "Stickers",
      "Kiss-cut sticker sheets, 4 x 6in.",
      1.1,
    ),
    S(
      "Holographic Stickers",
      "Stickers",
      "Holographic die-cut stickers, 3in.",
      0.8,
    ),
    S("Clear Stickers", "Stickers", "Clear vinyl stickers, 3in.", 0.6),
    S(
      "Bumper Stickers",
      "Stickers",
      "Outdoor bumper stickers, 3 x 10in.",
      0.95,
    ),
    S("Window Decals", "Stickers", "Static-cling window decals.", 1.3),
    S(
      "Round Roll Labels 2in",
      "Labels",
      "Roll labels for jars and bottles, 2in round.",
      0.14,
    ),
    S("Rectangle Roll Labels", "Labels", "Roll labels, 2 x 4in.", 0.18),
    S("Custom Bottle Labels", "Labels", "Waterproof bottle labels.", 0.22),
    S("Posters 12x18in", "Posters", "Full-colour posters, 12 x 18in.", 4.2),
    S("Posters 18x24in", "Posters", "Full-colour posters, 18 x 24in.", 6.5),
    S("Posters 24x36in", "Posters", "Full-colour posters, 24 x 36in.", 11),
    S("Business Cards Matte", "Cards", "Matte business cards.", 0.12),
    S("Business Cards Gloss", "Cards", "Gloss business cards.", 0.12),
    S("Business Cards Soft-Touch", "Cards", "Soft-touch laminated cards.", 0.2),
    S(
      "Business Cards Recycled",
      "Cards",
      "Recycled kraft business cards.",
      0.15,
    ),
    S("Flyers A5", "Print", "A5 flyers, double-sided.", 0.18),
    S("Flyers A4", "Print", "A4 flyers, double-sided.", 0.3),
    S("Postcards 4x6in", "Print", "Postcards, 4 x 6in.", 0.22),
    S("Tri-Fold Brochures", "Print", "Tri-fold brochures.", 0.55),
    S("Booklets 8-Page", "Print", "Saddle-stitched 8-page booklets.", 1.6),
    S("Catalogs 24-Page", "Print", "24-page perfect-bound catalogs.", 3.2),
    S(
      "Custom Printed Notebooks",
      "Print",
      "Notebooks with custom printed covers.",
      4.5,
    ),
    S(
      "Printed Wall Calendars",
      "Print",
      "12-month custom wall calendars.",
      6.5,
    ),
    S("Greeting Cards", "Cards", "Folded greeting cards with envelopes.", 1.4),
    S("Printed Thank-You Cards", "Cards", "Custom thank-you cards.", 0.6),
    S("Table Tents", "Print", "Folded table tents.", 0.5),
    S("Menus", "Print", "Laminated menus.", 1.2),
    S("Event Tickets", "Print", "Numbered event tickets.", 0.16),
    S("Tyvek Wristbands", "Print", "Numbered Tyvek wristbands.", 0.12),
    S("Vinyl Banner 3x6ft", "Signage", "Outdoor vinyl banner.", 24, {
      tiers: ["1-4", "5-9", "10-24", "25+"],
      factors: [1, 0.9, 0.8, 0.7],
    }),
    S("Retractable Banner", "Signage", "Retractable banner stand.", 62, {
      tiers: ["1-4", "5-9", "10-24", "25+"],
      factors: [1, 0.92, 0.85, 0.8],
      kind: "supply",
    }),
    S(
      "Buttons 1.25in",
      "Buttons and Magnets",
      "Pin-back buttons, 1.25in.",
      0.55,
    ),
    S(
      "Buttons 2.25in",
      "Buttons and Magnets",
      "Pin-back buttons, 2.25in.",
      0.75,
    ),
    S("Fridge Magnets", "Buttons and Magnets", "Flexible magnets.", 0.7),
    S(
      "Sublimated Lanyards",
      "Lanyards",
      "Full-colour dye-sublimated lanyards.",
      1.9,
    ),
    S(
      "Tote Screen Printing (1 color)",
      "Screen Printing",
      "One-color screen print on customer or supplied totes.",
      1.5,
      {
        tiers: ["25-49", "50-99", "100-249", "250+"],
        factors: [1, 0.85, 0.7, 0.6],
      },
    ),
    S(
      "T-Shirt Screen Printing (1 color, 1 location)",
      "Screen Printing",
      "One-color screen print.",
      1.75,
      {
        tiers: ["25-49", "50-99", "100-249", "250+"],
        factors: [1, 0.85, 0.7, 0.6],
      },
    ),
    S(
      "T-Shirt Screen Printing (2 color, 1 location)",
      "Screen Printing",
      "Two-color screen print.",
      2.6,
      {
        tiers: ["25-49", "50-99", "100-249", "250+"],
        factors: [1, 0.85, 0.7, 0.6],
      },
    ),
    S("DTF Transfer 4in", "Transfers", "Direct-to-film transfers, 4in.", 0.9),
    S("DTF Transfer 10in", "Transfers", "Direct-to-film transfers, 10in.", 2.4),
    S(
      "Heat Transfer Vinyl",
      "Transfers",
      "Cut heat transfer vinyl lettering.",
      1.3,
    ),
    S(
      "Mug Sublimation",
      "Sublimation",
      "Full-wrap sublimation on ceramic mugs.",
      3.8,
    ),
    S("Wedding Invitations", "Cards", "Custom wedding invitation suites.", 2.8),
    S("Packaging Inserts", "Print", "Printed packaging inserts.", 0.2),
    S("Printed Hangtags", "Print", "Custom hangtags.", 0.28),
    S(
      "Printed Shopping Bags",
      "Print",
      "Custom printed kraft shopping bags.",
      1.7,
    ),
    S(
      "Custom Playing Card Decks",
      "Print",
      "Custom printed 54-card decks.",
      4.2,
    ),
    fee(
      R,
      "Screen Setup Fee (per screen)",
      "Setup",
      "One-time setup per screen.",
      25,
      "transform",
      ["setup-fee"],
    ),
    fee(
      R,
      "Digital Mockup and Art Proof",
      "Setup",
      "Digital proof before production.",
      15,
      "transform",
      ["setup-fee"],
    ),
    fee(
      R,
      "Physical Sample Proof",
      "Samples",
      "One physical pre-production sample.",
      30,
      "transform",
      ["sample"],
    ),
    fee(
      R,
      "Rush 48h Print Surcharge",
      "Rush",
      "Per-order surcharge for 48-hour print turnaround.",
      80,
      "transform",
      ["rush"],
    ),
    fee(
      R,
      "Design Assistance (per hour)",
      "Design",
      "Design help from a print specialist.",
      60,
      "transform",
    ),
    fee(
      R,
      "Pantone Color Match",
      "Setup",
      "Pantone color matching per order.",
      20,
      "transform",
      ["setup-fee"],
    ),
    capacity(R, "Print Capacity - Pieces per Day", 3000, "transform"),
  ];
  return out;
}

// ---------------------------------------------------------------- Molecule storefront (ready-made kits)
const KITS = [
  [
    "New-Hire Onboarding Kit",
    "Hoodie, insulated bottle, notebook and pen in a branded box.",
    58,
  ],
  ["Hackathon Swag Kit", "Tee, sticker pack and water bottle.", 24],
  ["Conference Attendee Swag Bag", "Tote, notebook, pen and lanyard.", 18],
  ["Wedding Welcome Box", "Snacks, water and a local welcome card.", 26],
  ["Corporate Gift Box", "Premium bottle, notebook set and snacks.", 65],
  ["Client Appreciation Box", "Candle, coffee and chocolate.", 48],
  ["Startup Launch Kit", "Hoodie, cap, stickers and a laptop sleeve.", 72],
  ["Team Spirit Pack", "Tee, cap and drawstring bag.", 39],
  ["Graduation Gift Set", "Frame, pen set and snacks.", 34],
  ["Holiday Snack and Mug Box", "Ceramic mug with cocoa and cookies.", 29],
  ["Employee Appreciation Box", "Tumbler, snacks and a thank-you card.", 44],
  ["Sports Team Fan Pack", "Tee, cap and flying disc.", 33],
  ["Event Volunteer Kit", "Tee, lanyard and water bottle.", 21],
  ["Influencer PR Box", "Product, tote and hand-written card.", 55],
  [
    "Product Launch Mailer Kit",
    "Branded mailer box with inserts and samples.",
    37,
  ],
  ["Fundraiser Merch Pack", "Tee, sticker and button.", 27],
  ["Alumni Merch Bundle", "Hoodie, mug and pennant.", 41],
  ["Referral Reward Kit", "Bottle, snacks and a discount card.", 31],
  ["Birthday Celebration Box", "Candle, chocolate and a card.", 28],
  ["Thank-You Box", "Tea, cookies and a card.", 23],
  ["Team Retreat Welcome Kit", "Notebook, bottle, cap and snacks.", 46],
  ["Race Day Runner Kit", "Tee, towel and bottle.", 30],
  ["Coffee Lover Gift Set", "Mug, coffee and cookies.", 32],
  ["Wellness Box", "Yoga towel, hand cream and tea.", 40],
  ["Movie Night Box", "Popcorn, blanket and snacks.", 25],
  ["Outdoor Adventure Kit", "Bottle, cooler bag and camp mug.", 52],
  ["Back-to-School Kit", "Notebooks, pens and backpack.", 27],
  ["Pet Parent Box", "Bandana, toy and treats.", 35],
  ["Housewarming Box", "Candle, cutting board and snacks.", 43],
  ["Teacher Appreciation Set", "Mug, pen set and chocolate.", 22],
  ["Club Membership Kit", "Tee, pin, sticker and card.", 20],
  ["Vegan Snack Sampler Box", "Twelve assorted vegan snacks.", 26],
  ["Desk Setup Kit", "Desk pad, charger and notebook.", 60],
  ["Travel Essentials Kit", "Duffel, luggage tag and towel.", 45],
  ["Custom Merch Pack (build your own)", "Choose your own mix of items.", 30],
];
function molecule() {
  const q = ["10 kits", "25 kits", "50 kits", "100 kits"];
  const f = [1, 0.93, 0.86, 0.8];
  return KITS.map(([title, desc, base]) =>
    build("molecule", {
      title,
      type: "Kits and Bundles",
      desc: `${desc} Assembled to order from network merchants.`,
      tags: ["bundle", "made-to-order"],
      kind: "bundle",
      options: { Quantity: q },
      price: (c) => base * f[q.indexOf(val(c, "Quantity"))],
      stock: null,
      exact: true,
    }),
  );
}

export const roleForStore = (handle) =>
  Object.entries(MERCHANT_IDS).find(
    ([role, id]) =>
      handle === role ||
      handle.startsWith(`${role}-`) ||
      handle === id ||
      handle.startsWith(`${id}-`),
  )?.[0] ?? handle.split("-")[0];
export function catalogFor(role) {
  switch (roleForStore(role)) {
    case "basegoods":
      return baseGoods();
    case "stitchworks":
      return embroidery("stitchworks", 1, 5, 20);
    case "threadforge":
      return embroidery("threadforge", 1.13, 4, 180);
    case "needlenorth":
      return embroidery("needlenorth", 1.14, 3, 200);
    case "laserlab":
      return laserLab();
    case "packship":
      return packShip();
    case "snackbox":
      return snackBox();
    case "printpress":
      return printPress();
    case "molecule":
      return molecule();
    default:
      return [];
  }
}

export const STITCHWORKS_CAPACITY_EVIDENCE = [
  { source: "web", unitsPerDay: 100 },
  { source: "document", unitsPerDay: 50 },
  { source: "fresh-outage-note", unitsPerDay: 20 },
];

export function releaseCatalogFor(inputRole) {
  const role = roleForStore(inputRole);
  const item = (title, type, price, kind, tags, description, stock = null) =>
    build(role, {
      title: `Release Demo ${title}`,
      type,
      price,
      kind,
      tags: ["release-demo", ...tags],
      desc: description,
      stock,
      exact: true,
    });
  const goods = (title, type, price, tags, description) =>
    item(
      title,
      type,
      price,
      "supply",
      ["lead_days:1", ...tags],
      description,
      [1000, 1000],
    );
  switch (role) {
    case "basegoods":
      return [
        goods(
          "Premium Black Cotton Hoodie",
          "Hoodies",
          12,
          [
            "output:hoodie",
            "material:cotton",
            "color:black",
            "no-leather",
            "no-polyester",
          ],
          "100% cotton black hoodie; no leather or polyester. Synthetic stock 1,000 units; one business day.",
        ),
        goods(
          "Black Engravable Bottle",
          "Drinkware",
          5,
          [
            "output:bottle",
            "material:stainless-steel",
            "color:black",
            "no-leather",
            "no-polyester",
          ],
          "Black stainless-steel bottle; suitable for individual name engraving. Synthetic stock 1,000; one business day.",
        ),
      ];
    case "threadforge":
    case "needlenorth":
    case "stitchworks": {
      const perDay = role === "stitchworks" ? 20 : 400;
      return [
        item(
          "Hoodie Logo Embroidery",
          "Embroidery",
          role === "needlenorth" ? 5.1 : 4.5,
          "transform",
          [
            "capability:embroidery",
            "input:hoodie",
            "output:hoodie",
            "lead_days:1",
            `units_per_day:${perDay}`,
          ],
          `Synthetic logo embroidery, one business day plus quantity/capacity limits. Capacity ${perDay}/day.${role === "stitchworks" ? " Conflicting synthetic evidence: web 100/day, document 50/day, fresh outage note 20/day. Do not collapse this conflict into verified availability." : " Synthetic acceptance capacity only; not verified real availability."}`,
        ),
        capacity(role, "Release Demo Embroidery Capacity", perDay, "transform"),
      ];
    }
    case "laserlab":
      return [
        item(
          "Named Bottle Engraving",
          "Engraving",
          3.2,
          "transform",
          [
            "capability:engraving",
            "input:bottle",
            "output:bottle",
            "lead_days:1",
            "units_per_day:400",
          ],
          "Individual supplied names engraved on each bottle. One business day; synthetic capacity 400/day.",
        ),
        item(
          "Engraving Setup",
          "Setup",
          35,
          "transform",
          ["capability:engraving", "setup-fee"],
          "One setup fee per order; add to total once.",
        ),
      ];
    case "snackbox":
      return [
        goods(
          "Vegan Snack Pack",
          "Snacks",
          3,
          ["output:snacks", "diet:vegan"],
          "One individually wrapped vegan snack pack per kit. Allergen facts unspecified; do not infer allergen safety. One business day.",
        ),
      ];
    case "packship":
      return [
        item(
          "Individual Kit Packaging",
          "Assembly",
          2,
          "assemble",
          [
            "capability:assembly",
            "individual-packaging",
            "lead_days:0.5",
            "units_per_day:800",
          ],
          "One black recycled cardboard box with paper cushioning per kit; individual packaging; no leather or polyester. Half a business day, synthetic 800/day.",
        ),
        item(
          "Kit Fulfillment",
          "Fulfillment",
          2,
          "fulfill",
          ["capability:fulfillment", "lead_days:1", "units_per_day:800"],
          "Synthetic local fulfillment rate per individually packaged kit; one business day and 800/day. Not a verified carrier quote.",
        ),
      ];
    case "molecule":
      return [];
    default:
      return [];
  }
}
