"use client";

import { useCallback, useEffect, useState } from "react";
import type {
  StoreAnalytics,
  StoreCatalog,
  StoreCustomers,
  StoreList,
  StoreOrders,
  StoreProvenance,
  StoreSummary,
} from "@molecule/contracts";
import {
  getStoreAnalytics,
  getStoreCatalog,
  getStoreCustomers,
  getStoreOrders,
  getStores,
} from "../lib/api";
import { dateLabel, humanize, variantAdminUrl } from "../lib/workspace";
import { Empty } from "./WorkspacePanels";

type Tab = "catalog" | "orders" | "customers" | "analytics";
const tabs: { key: Tab; label: string }[] = [
  { key: "catalog", label: "Catalog" },
  { key: "orders", label: "Orders" },
  { key: "customers", label: "Customers" },
  { key: "analytics", label: "Analytics" },
];

/**
 * Provenance is stated on every panel, never inferred by the reader.
 *
 * `synthetic_only` is the important one: those records have no live counterpart and never
 * will, because the scope that would produce them is not granted. Saying so on the panel is
 * what keeps a demo surface from being read as operational truth.
 */
function ProvenanceNote({ provenance }: { provenance: StoreProvenance }) {
  if (provenance === "provider_backed") return null;
  const synthetic = provenance === "synthetic_only";
  return (
    <p className={synthetic ? "inline-warning" : "muted small"} role="note">
      {synthetic
        ? "Synthetic · no live equivalent. These records are generated locally for display and are never used to plan, quote or certify work."
        : "Synthetic · generated by the local fake store. Not a real merchant record."}
    </p>
  );
}

function money(amount: string, currency: string) {
  const value = Number(amount);
  return Number.isFinite(value)
    ? new Intl.NumberFormat(undefined, {
        style: "currency",
        currency: currency || "CAD",
      }).format(value)
    : `${amount} ${currency}`;
}

/** A tiny inline bar chart. Deliberately plain: it reports values, it does not decorate. */
function SalesBars({
  daily,
  currency,
}: {
  daily: StoreAnalytics["daily"];
  currency: string;
}) {
  const peak = daily.reduce(
    (max, point) => Math.max(max, Number(point.grossSales)),
    0,
  );
  if (!peak) return null;
  return (
    <ul className="store-bars">
      {daily.map((point) => {
        const value = Number(point.grossSales);
        return (
          <li key={point.day}>
            <span
              className="store-bar"
              style={{ height: `${Math.max(2, (value / peak) * 100)}%` }}
              aria-hidden="true"
            />
            <span className="store-bar-label">
              {point.day.slice(5)} · {money(point.grossSales, currency)} ·{" "}
              {point.orderCount} orders
            </span>
          </li>
        );
      })}
    </ul>
  );
}

function CatalogPanel({ data }: { data: StoreCatalog }) {
  return (
    <>
      <ProvenanceNote provenance={data.provenance} />
      <p className="muted small">
        Showing {data.products.length} of {data.total} products · captured{" "}
        {dateLabel(data.capturedAt, true)}
      </p>
      <ul className="store-list">
        {data.products.map((product) => (
          <li key={product.productGid}>
            <div className="store-row-head">
              <strong>{product.title}</strong>
              <span className="muted small">{product.status}</span>
            </div>
            <p className="muted small">
              {product.vendor ?? "Unknown vendor"} ·{" "}
              {product.productType ?? "Uncategorised"} ·{" "}
              <code>{product.handle}</code>
            </p>
            <table className="store-table">
              <thead>
                <tr>
                  <th scope="col">SKU</th>
                  <th scope="col">Variant</th>
                  <th scope="col">Price</th>
                  <th scope="col">Available</th>
                </tr>
              </thead>
              <tbody>
                {product.variants.map((variant) => {
                  const admin = variantAdminUrl(
                    data.shopDomain,
                    variant.variantGid,
                  );
                  return (
                    <tr key={variant.variantGid}>
                      <td>
                        {admin ? (
                          <a href={admin} target="_blank" rel="noreferrer">
                            <code>{variant.sku ?? "—"}</code>
                          </a>
                        ) : (
                          <code>{variant.sku ?? "—"}</code>
                        )}
                      </td>
                      <td>{variant.title ?? "—"}</td>
                      <td>
                        {variant.price
                          ? money(variant.price, variant.currency ?? "CAD")
                          : "—"}
                      </td>
                      <td>
                        {!variant.tracked
                          ? "Not tracked"
                          : // A null quantity is an unknown, not a zero.
                            (variant.available ?? "Unknown")}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </li>
        ))}
      </ul>
    </>
  );
}

function OrdersPanel({ data }: { data: StoreOrders }) {
  return (
    <>
      <ProvenanceNote provenance={data.provenance} />
      <p className="muted small">
        Showing {data.orders.length} of {data.total} orders · captured{" "}
        {dateLabel(data.capturedAt, true)}
      </p>
      <ul className="store-list">
        {data.orders.map((order) => (
          <li key={order.orderGid}>
            <div className="store-row-head">
              <strong>{order.name}</strong>
              <span>{money(order.total, order.currency)}</span>
            </div>
            <p className="muted small">
              {dateLabel(order.createdAt, true)} ·{" "}
              {humanize(order.financialStatus ?? "unknown")} ·{" "}
              {humanize(order.fulfillmentStatus ?? "unknown")}
              {order.customerName ? ` · ${order.customerName}` : ""}
            </p>
            <table className="store-table">
              <thead>
                <tr>
                  <th scope="col">Item</th>
                  <th scope="col">SKU</th>
                  <th scope="col">Qty</th>
                  <th scope="col">Total</th>
                </tr>
              </thead>
              <tbody>
                {order.lineItems.map((line) => (
                  <tr key={line.lineItemGid}>
                    <td>{line.title}</td>
                    <td>
                      <code>{line.sku ?? "—"}</code>
                    </td>
                    <td>{line.quantity}</td>
                    <td>{money(line.totalPrice, order.currency)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </li>
        ))}
      </ul>
    </>
  );
}

function CustomersPanel({ data }: { data: StoreCustomers }) {
  return (
    <>
      <ProvenanceNote provenance={data.provenance} />
      <p className="muted small">
        Showing {data.customers.length} of {data.total} customers · captured{" "}
        {dateLabel(data.capturedAt, true)}
      </p>
      <table className="store-table">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Orders</th>
            <th scope="col">Spent</th>
          </tr>
        </thead>
        <tbody>
          {data.customers.map((customer) => (
            <tr key={customer.customerGid}>
              <td>{customer.displayName}</td>
              <td>{customer.email ?? "—"}</td>
              <td>{customer.orderCount}</td>
              <td>{money(customer.amountSpent, customer.currency)}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </>
  );
}

function AnalyticsPanel({ data }: { data: StoreAnalytics }) {
  return (
    <>
      <ProvenanceNote provenance={data.provenance} />
      <dl className="detail-grid">
        <div>
          <dt>Orders</dt>
          <dd>{data.totals.orderCount}</dd>
        </div>
        <div>
          <dt>Units</dt>
          <dd>{data.totals.units}</dd>
        </div>
        <div>
          <dt>Gross sales</dt>
          <dd>{money(data.totals.grossSales, data.currency)}</dd>
        </div>
        <div>
          <dt>Average order</dt>
          <dd>{money(data.totals.averageOrderValue, data.currency)}</dd>
        </div>
      </dl>
      <h3>Daily sales</h3>
      <SalesBars daily={data.daily} currency={data.currency} />
      <h3>Top products</h3>
      <table className="store-table">
        <thead>
          <tr>
            <th scope="col">Product</th>
            <th scope="col">Units</th>
            <th scope="col">Gross sales</th>
          </tr>
        </thead>
        <tbody>
          {data.topProducts.map((product) => (
            <tr key={product.productGid ?? product.title}>
              <td>{product.title}</td>
              <td>{product.units}</td>
              <td>{money(product.grossSales, data.currency)}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </>
  );
}

/**
 * Browse the stores mirrored into the read model: their catalog, orders, customers and sales.
 *
 * Reads the same routes in live and fake mode; only the provenance label differs.
 */
export function StoreConsole() {
  const [stores, setStores] = useState<StoreList | null>(null);
  const [selected, setSelected] = useState<string | null>(null);
  const [tab, setTab] = useState<Tab>("catalog");
  const [panel, setPanel] = useState<
    StoreCatalog | StoreOrders | StoreCustomers | StoreAnalytics | null
  >(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const controller = new AbortController();
    getStores(controller.signal)
      .then((list) => {
        setStores(list);
        setSelected((current) => current ?? list.stores[0]?.shopDomain ?? null);
      })
      .catch((cause: unknown) => {
        if (!controller.signal.aborted)
          setError(
            cause instanceof Error ? cause.message : "Could not load stores.",
          );
      })
      .finally(() => setLoading(false));
    return () => controller.abort();
  }, []);

  const load = useCallback(
    (domain: string, next: Tab, signal: AbortSignal) => {
      const readers = {
        catalog: getStoreCatalog,
        orders: getStoreOrders,
        customers: getStoreCustomers,
        analytics: getStoreAnalytics,
      } as const;
      return readers[next](domain, signal);
    },
    [],
  );

  useEffect(() => {
    if (!selected) return;
    const controller = new AbortController();
    setPanel(null);
    setError(null);
    load(selected, tab, controller.signal)
      .then((data) => setPanel(data))
      .catch((cause: unknown) => {
        if (!controller.signal.aborted)
          setError(
            cause instanceof Error
              ? cause.message
              : "Could not load this store.",
          );
      });
    return () => controller.abort();
  }, [selected, tab, load]);

  if (loading) return <p className="muted">Loading stores…</p>;

  if (!stores?.stores.length) {
    return (
      <Empty title="No stores mirrored yet">
        Run the Shopify sync to mirror store catalogs into the read model. With
        SHOPIFY_MODE=fake this needs no credentials.
      </Empty>
    );
  }

  const current: StoreSummary | undefined = stores.stores.find(
    (store) => store.shopDomain === selected,
  );

  return (
    <section className="store-console">
      <header>
        <h2>Stores</h2>
        <p className="muted small">
          {stores.stores.length} stores ·{" "}
          {stores.mode === "live"
            ? "Live Shopify"
            : stores.mode === "fake"
              ? "Local synthetic stores"
              : "Demo commerce"}
        </p>
      </header>

      <nav className="store-picker" aria-label="Stores">
        {stores.stores.map((store) => (
          <button
            key={store.shopDomain}
            type="button"
            className={store.shopDomain === selected ? "active" : undefined}
            aria-current={store.shopDomain === selected}
            onClick={() => setSelected(store.shopDomain)}
          >
            <strong>{store.merchantName}</strong>
            <span className="muted small">
              {store.productCount} products · {store.orderCount} orders
            </span>
          </button>
        ))}
      </nav>

      {current && (
        <p className="muted small">
          <code>{current.shopDomain}</code> · {current.variantCount} variants ·{" "}
          {current.trackedVariantCount} tracked · synced{" "}
          {dateLabel(current.syncedAt, true)}
        </p>
      )}

      <div className="store-tabs" role="tablist" aria-label="Store data">
        {tabs.map((entry) => (
          <button
            key={entry.key}
            type="button"
            role="tab"
            aria-selected={entry.key === tab}
            className={entry.key === tab ? "active" : undefined}
            onClick={() => setTab(entry.key)}
          >
            {entry.label}
          </button>
        ))}
      </div>

      <div role="tabpanel">
        {error && <p className="inline-warning">{error}</p>}
        {!error && !panel && <p className="muted">Loading…</p>}
        {panel && "products" in panel && <CatalogPanel data={panel} />}
        {panel && "orders" in panel && <OrdersPanel data={panel} />}
        {panel && "customers" in panel && <CustomersPanel data={panel} />}
        {panel && "totals" in panel && <AnalyticsPanel data={panel} />}
      </div>
    </section>
  );
}
